from lib import *

numeroAlumno = pedirNumeroAlumno()
nodoRaiz2 = int(numeroAlumno)
archivo = pedirArchivo()
print('')
print('Números en archivo, el rojo es mi número:')
imprimirMatriz(archivo, numeroAlumno)
print('')
print('Arbol armado por extensión:')
nodoRaiz = arbolOrdenado(archivo)
print('')
print('Recorridos de Árbol:\n')
arrLVR = LVR(nodoRaiz, arr=[])
print(f'In order: \n{arrLVR}')
arrVLR = VLR(nodoRaiz, arr=[])
print(f'Pre order: \n{arrVLR}')
arrLRV = LRV(nodoRaiz, arr=[])
print(f'Post order: \n{arrLRV}')
print('')
print('Árbol armado por ordenamiento:')
nodoArbOrd = arbolNumOrdenado(archivo,nodoRaiz2)
print('')
print('Recorrido del Árbol Ordenado: ')
arr2LRV = LRV(nodoArbOrd, arr=[])
print(arr2LRV)